services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
        - .env
    volumes:
      - ${VAULTWARDEN_DATA_DIR}:/data
    networks:
      - default
      - services-network

networks:
  default:
    name: vaultwarden-network
    driver: bridge
  services-network:
    external: true
