services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    env_file:
        - .env
    ports:
      - '80:80'
      # - '80:81' # Needs to be disabled after initial setup
      - '443:443'
    volumes:
      - ${NGINX_PROXY_MANAGER_DATA_DIR}:/data
      - ${NGINX_PROXY_MANAGER_SSL_CERT_DIR}:/etc/letsencrypt
    networks:
      - default
      - services-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  default:
    name: nginx-proxy-manager-network
    driver: bridge
  services-network:
    external: true
